import 'package:flutter/material.dart';
import '../../core/theme/app_colors.dart';
import '../../shared/widgets/button.dart';

class DisclaimerScreen extends StatelessWidget {
  final String disclaimerText = """This application is provided strictly for educational, informational, and demonstrational purposes only. It is not intended for use in real trading, financial decision-making, or any form of actual cryptocurrency transaction.This application is not affiliated with, endorsed by, sponsored by, or in any way connected to Bitkub, Bitkub Online Co., Ltd., or any of its subsidiaries, products, platforms, or services. Any references to Bitkub are made solely for explanatory or comparative purposes. No representation is made that this application reflects, emulates, or reproduces any official Bitkub systems, features, data, or functionalities.All data, examples, simulations, and outputs generated by this application are entirely fictional and should not be interpreted as real market information or financial advice. The developers and owners of this application shall not be held liable for any misunderstanding, misuse, or damages arising from reliance on the information or features contained herein. By using this application, you acknowledge and agree to this disclaimer and accept all associated risks and limitations.""";

  const DisclaimerScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // Use the standard dark background gradient
      body: Container(
        width: double.infinity,
        height: double.infinity,
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.50, -0.00),
            end: Alignment(0.50, 1.00),
            colors: [AppColors.backgroundGradient1, AppColors.backgroundGradient2],
          ),
        ),
        child: SafeArea(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 32),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const SizedBox(height: 30),

                // --- Title ---
                const Text(
                  'Disclaimer',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: AppColors.textPrimary,
                    fontSize: 32,
                    fontFamily: 'Montserrat',
                    fontWeight: FontWeight.w800,
                  ),
                ),
                const SizedBox(height: 30),

                Expanded(
                  child: Container(
                    padding: const EdgeInsets.all(24),
                    decoration: BoxDecoration(
                      // Use a subtle, dark background for the box
                      color: AppColors.surfacePrimary.withOpacity(0.9), 
                      borderRadius: BorderRadius.circular(20),
                    ),
                    child: SingleChildScrollView(
                      child: Text(
                        disclaimerText,
                        style: const TextStyle(
                          color: AppColors.textPrimary,
                          fontSize: 14,
                          fontFamily: 'Montserrat',
                          fontWeight: FontWeight.w400,
                          height: 1.5,
                        ),
                      ),
                    ),
                  ),
                ),
                const SizedBox(height: 30),

                // --- Proceed Button ---
                Button(
                  label: 'Proceed',
                  type: ButtonType.primary,
                  onPressed: () {
                    debugPrint('Proceeding from disclaimer...');
                  },
                ),
                const SizedBox(height: 30),
              ],
            ),
          ),
        ),
      ),
    );
  }
}